version: '2'
services:

  data-volume:
    container_name: docker-data
    image: busybox
    volumes:
      - "${SRC_DIR}:/go/src/app"
      - ./volume/db:/var/lib/mysql
      - ./volume/log/mysql:/var/log/mysql

  web-app:
    container_name: docker-app
    image: golang:1.11-alpine3.8
    working_dir: /go/src/app
    ports:
      - 80:80
    links:
      - db
    volumes_from:
      - data-volume
    tty: true

  db:
    container_name: docker-mysql57
    image: mysql:5.7
    working_dir: /var/lib/mysql
    command: mysqld --sql_mode=""
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes_from:
      - data-volume
