version: '2'
services:
  # Mount Volumes
  data-volume:
    container_name: docker-data
    image: busybox
    volumes:
      # Data
      - .:/go/src/app
      - ./volume/db:/var/lib/postgresql/data

  web-app:
    container_name: app
    image: golang:1.13-alpine
    working_dir: /go/src/app
    ports:
      - 80:80
    links:
      - db
    volumes_from:
      - data-volume
    tty: true

  db:
    container_name: docker-postgres12
    image: postgres:12-alpine
    working_dir: /var/lib/postgres/data
    ports:
      - 3306:3306
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      MYSQL_ROOT_PASSWORD: password
      LANG: ja_JP.utf8
    volumes_from:
      - data-volume
    restart: always
    user: root
