version: '2'
services:

  data-volume:
    container_name: docker-data
    image: busybox
    volumes:
      - "${SRC_DIR}:/var/www/html"
      - ./volume/db:/var/lib/mysql
      - ./volume/redis:/data
      - ./volume/log/nginx:/var/log/nginx
      - ./volume/log/php-fpm:/var/log/php-fpm
      - ./volume/log/mysql:/var/log/mysql
        # - ./volume/log/app:/var/www/html/htdocs/logs
      - ./volume/log/app:/var/www/html/logs

  web:
    container_name: docker-nginx
    build: ./nginx
    ports:
      - 80:80
    links:
      - app
    volumes_from:
      - data-volume

  app:
    container_name: docker-php7fpm
    build: ./php-fpm
    ports:
      - 9000:9000
    links:
      - db
    volumes_from:
      - data-volume

  kvs:
    container_name: docker-redis
    image: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes_from:
      - data-volume

  db:
    container_name: docker-mysql57
    image: mysql:5.7
    command: mysqld --sql_mode="" --innodb-use-native-aio=0
    ports:
      - 3306:3306
    volumes_from:
      - data-volume
    environment:
      MYSQL_ROOT_PASSWORD: password
